### ISSUE TITLE
Blank transparent PNGs, empty grey map

### ISSUE THREAD

**Issue by akkana** [JasonSanford/tileify-ags-proxy#6]
This might be just me entering the wrong URL, but I'm seeing a blank grey map at http://tileify-ags.herokuapp.com/ for every URL I try, including the default URL when I first visit the page. The other URLs I've tried in the ArcGIS Server URL field:
https://gis.blm.gov/arcgis/rest/services/lands/BLM_Natl_SMA_Cached_without_PriUnk/MapServer/ (which used to work),
https://gis1.usgs.gov/arcgis/rest/services/padus2_1/FeeManagers/MapServer/ (the URL I'm seeing in the network inspector for repeated downloads if I go to https://maps.usgs.gov/padus/),
or just the top-level URL for that map, https://maps.usgs.gov/padus/

Has arcgis changed something about their pages? Or am I doing something wrong? Tileify is very slick and I've used it before, and I know it used to work great. Thanks for writing it!

**Comment by JasonSanford** [comment]
There were a couple issues here. The basemaps provided by Mapbox where dead as well as the tileified overlay. I've switched to the OSM provided tiled basemap and a new tileified overlay for the example. Everything else appears to be working fine.
